version: '1.0.0-pre{build}'
branches:
  only:
    - master
image: Visual Studio 2017
install:
  - nuget sources add -name core -source https://ci.appveyor.com/nuget/core-2nbdf5dfgymf
  - nuget restore
configuration: Debug
before_build:
  - ps: |
      $zeroPaddedBuildNumber = [convert]::ToInt32($env:appveyor_build_number, 10).ToString("000000")
      Update-AppveyorBuild -Version "1.0.0-pre$zeroPaddedBuildNumber"
      $xmlPath = "$env:appveyor_build_folder\Vostok.Logging.Serilog\Vostok.Logging.Serilog.csproj"
      $xml = [xml](get-content $xmlPath)
      $version = $xml.CreateElement("Version")
      $versionText = $xml.CreateTextNode($env:appveyor_build_version)
      $version.AppendChild($versionText)
      $xml.Project.PropertyGroup.AppendChild($version)
      $xml.Save($xmlPath)
  - ps: |
      $zeroPaddedBuildNumber = [convert]::ToInt32($env:appveyor_build_number, 10).ToString("000000")
      Update-AppveyorBuild -Version "1.0.0-pre$zeroPaddedBuildNumber"
      $xmlPath = "$env:appveyor_build_folder\Vostok.Logging.Log4Net\Vostok.Logging.Log4Net.csproj"
      $xml = [xml](get-content $xmlPath)
      $version = $xml.CreateElement("Version")
      $versionText = $xml.CreateTextNode($env:appveyor_build_version)
      $version.AppendChild($versionText)
      $xml.Project.PropertyGroup.AppendChild($version)
      $xml.Save($xmlPath)
  - ps: |
      $zeroPaddedBuildNumber = [convert]::ToInt32($env:appveyor_build_number, 10).ToString("000000")
      Update-AppveyorBuild -Version "1.0.0-pre$zeroPaddedBuildNumber"
      $xmlPath = "$env:appveyor_build_folder\Vostok.Instrumentation.WebApi\Vostok.Instrumentation.WebApi.csproj"
      $xml = [xml](get-content $xmlPath)
      $version = $xml.CreateElement("Version")
      $versionText = $xml.CreateTextNode($env:appveyor_build_version)
      $version.AppendChild($versionText)
      $xml.Project.PropertyGroup.AppendChild($version)
      $xml.Save($xmlPath)
  - ps: |
      $zeroPaddedBuildNumber = [convert]::ToInt32($env:appveyor_build_number, 10).ToString("000000")
      Update-AppveyorBuild -Version "1.0.0-pre$zeroPaddedBuildNumber"
      $xmlPath = "$env:appveyor_build_folder\Vostok.Instrumentation.Topshelf\Vostok.Instrumentation.Topshelf.csproj"
      $xml = [xml](get-content $xmlPath)
      $version = $xml.CreateElement("Version")
      $versionText = $xml.CreateTextNode($env:appveyor_build_version)
      $version.AppendChild($versionText)
      $xml.Project.PropertyGroup.AppendChild($version)
      $xml.Save($xmlPath)
after_build:
  - ps: Get-ChildItem .\Vostok.Logging.Serilog\bin\Debug\Vostok.Logging.Serilog.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\Vostok.Logging.Log4Net\bin\Debug\Vostok.Logging.Log4Net.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\Vostok.Instrumentation.WebApi\bin\Debug\Vostok.Instrumentation.WebApi.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\Vostok.Instrumentation.Topshelf\bin\Debug\Vostok.Instrumentation.Topshelf.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
